on: 
  push:
  workflow_dispatch:
    inputs:
      dryRun:
        required: true
        default: true
        type: boolean
name: Test and publish
permissions:
  actions: write
  contents: write
jobs:
  test-action:
    uses: ./.github/workflows/test-action.yml
    secrets: inherit
  
  publish: 
    runs-on: ubuntu-latest
    needs: [test-action]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          dry_run: ${{ inputs.dryRun }}
        env:
            GITHUB_TOKEN: ${{ github.token }}

      - name: Push updates to branch for major version
        if: steps.semantic.outputs.new_release_published == 'true'
        run: "git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:refs/heads/v${{steps.semantic.outputs.new_release_major_version}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}