on: 
  workflow_dispatch:
    inputs:
      dryRun:
        required: true
        default: true
        type: boolean
name: Create release
permissions:
  actions: write
  contents: write
jobs:
  test-action:
    uses: ./.github/workflows/test-action.yml
    secrets: inherit
  
  publish: 
    runs-on: ubuntu-latest
    needs: [test-action]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          dry_run: ${{ inputs.dryRun }}
        env:
          GITHUB_TOKEN: ${{ github.token }}