on: 
  push:
  workflow_dispatch:
  schedule: 
    - cron: '0 12 * * 1,4'
name: Test Github Action
# permissions:
#   actions: write
jobs:
  cache-exact-key:
    runs-on: ubuntu-latest
    name: Cache exact key
    steps:
      - name: Cache
        uses: actions/cache@v3
        with:
          path: .
          key: exact-key

  cache-starts-with-key:
    runs-on: ubuntu-latest
    name: Cache key with random id at the end
    steps:
      - name: Cache
        uses: actions/cache@v3
        with:
          path: .
          key: starts-with-${{ github.run_id }}

  test-exact-key:
    runs-on: ubuntu-latest
    name: Test exact key mode
    needs: [cache-exact-key]
    steps:
      - name: Delete cache with exact key
        id: hello
        uses: DareFox/delete-cache-by-key@main
        with:
          key: exact-key
          mode: exact

  test-startsWith-key:
    runs-on: ubuntu-latest
    name: Test startsWith mode
    needs: [cache-starts-with-key]
    steps:
      - name: Delete cache that starts with 'starts-with-'
        id: hello
        uses: DareFox/delete-cache-by-key@main
        with:
          key: starts-with-
          mode: startsWith
      
